let arrTheme = [
    [
        "Mandalorian memory",
        "img/mandalorian/mudhorn.png",
        "url('img/mandalorian/land.png')",
        "url('img/mandalorian/mandalorian-end.jpg')",
        [
            "img/mandalorian/booba.png",
            "img/mandalorian/darkTrooper.png",
            "img/mandalorian/grogu.png",
            "img/mandalorian/grogu02.png",
            "img/mandalorian/jedi.png",
            "img/mandalorian/manda01.png",
            "img/mandalorian/manda02.png",
            "img/mandalorian/manda03.png",
            "img/mandalorian/manda04.png",
            "img/mandalorian/robot.png",
        ]
        ],
    [
        "Seigneur des anneaux",
        "img/lordOfRings/lotr01.png",
        "url('img/lordOfRings/middleEarth.jpg')",
        "url('img/lordOfRings/oneRing.jpg')",
        [
            "img/lordOfRings/aragorn.png",
            "img/lordOfRings/boromir.png",
            "img/lordOfRings/eye.png",
            "img/lordOfRings/frodo.png",
            "img/lordOfRings/gandalf.png",
            "img/lordOfRings/gimli.png",
            "img/lordOfRings/legolas.png",
            "img/lordOfRings/pipinMerry.png",
            "img/lordOfRings/ring.png",
            "img/lordOfRings/sam.png",
        ]
        ],
    [
        "Witcher memory",
        "img/the_witcher/logo01.png",
        "url('img/the_witcher/wild-hunt.jpg')",
        "url('img/the_witcher/witcher_end.jpg')",
        [
            "img/the_witcher/yennefer.jpg",
            "img/the_witcher/calanthe.jpg",
            "img/the_witcher/ciri.jpg",
            "img/the_witcher/duny.jpg",
            "img/the_witcher/jaskier.jpg",
            "img/the_witcher/pavetta.jpg",
            "img/the_witcher/the-witcher01.jpg",
            "img/the_witcher/the-witcher02.jpg",
            "img/the_witcher/tisaia.jpg",
            "img/the_witcher/triss.jpg",
        ]
    ],
    ]
